<?php
// auto-generated by sfPropelCrud
// date: 2008/08/15 16:06:02
?>
<?php use_helper('Object') ?>

<?php echo form_tag('advertise/update') ?>

<?php echo object_input_hidden_tag($advertise, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Advertiser name*:</th>
  <td><?php echo object_input_tag($advertise, 'getAdvertiserName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Company*:</th>
  <td><?php echo object_input_tag($advertise, 'getCompany', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($advertise, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Phone*:</th>
  <td><?php echo object_input_tag($advertise, 'getPhone', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Comment:</th>
  <td><?php echo object_textarea_tag($advertise, 'getComment', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($advertise->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'advertise/delete?id='.$advertise->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'advertise/show?id='.$advertise->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'advertise/list') ?>
<?php endif; ?>
</form>
