<?php
// auto-generated by sfPropelCrud
// date: 2008/08/15 16:06:02
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $advertise->getId() ?></td>
</tr>
<tr>
<th>Advertiser name: </th>
<td><?php echo $advertise->getAdvertiserName() ?></td>
</tr>
<tr>
<th>Company: </th>
<td><?php echo $advertise->getCompany() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $advertise->getEmail() ?></td>
</tr>
<tr>
<th>Phone: </th>
<td><?php echo $advertise->getPhone() ?></td>
</tr>
<tr>
<th>Comment: </th>
<td><?php echo $advertise->getComment() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $advertise->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'advertise/edit?id='.$advertise->getId()) ?>
&nbsp;<?php echo link_to('list', 'advertise/list') ?>
