<?php
// auto-generated by sfPropelCrud
// date: 2007/08/01 00:18:19
?>
<?php use_helper('Date','Text', 'Global', 'Tags') ?>

<?php foreach($photos as $photo): ?>
<?php $pic_thumbnail_url=path2url('/uploads/assets/photos/thumbnails/'.$photo->getFilename());?>
<div class="picture_thumbnail">
  <?php echo link_to(image_tag($pic_thumbnail_url, ''), 'photos/show?id='.$photo->getId())?>
    <div class="interested_block">
      <?php include_partial('photos/interested_user', array('photos' => $photo)) ?>
     </div>
  
       <?php $photo_owner=$photo->getAlbum()->getsfGuardUser()->getUsername();?>
	   from <?php echo link_to($photo_owner, 'user/'.$photo_owner) ?>			
</div>
<?php endforeach; ?>
<div class="pagination">
  <div id="photos_pager">
    <?php //echo pager_navigation($photos, $rule) ?>
  </div>
</div>