<?php
// auto-generated by sfPropelCrud
// date: 2007/08/01 00:18:19
?>
<?php use_helper('Date','Text', 'Global', 'Tags') ?>

<?php foreach($photos_pager->getResults() as $photos): ?>
<?php $pic_thumbnail_url=path2url('/uploads/assets/photos/thumbnails/'.$photos->getFilename());?>
<div class="picture_thumbnail">
  <?php echo link_to(image_tag($pic_thumbnail_url, 'alt=no picture'), 'photos/show?id='.$photos->getId())?>
    <div class="interested_block">
      <?php include_partial('photos/interested_user', array('photos' => $photos)) ?>
     </div>
  
       <?php //$photo_owner=$photos->getAlbum()->getsfGuardUser()->getUsername();?>
	          <?php $photo_owner=$photos->getsfGuardUser()->getUsername();?>

	   from <?php echo link_to(truncate_text($photo_owner, 10), 'user/'.$photo_owner) ?>			
</div>
<?php endforeach; ?>
<div class="pagination">
  <div id="photos_pager">
    <?php echo pager_navigation($photos_pager, $rule) ?>
  </div>
</div>