<?php
// auto-generated by sfPropelCrud
// date: 2007/08/01 00:18:19
?>

<?php use_helper('Date','Text', 'Global', 'Tags') ?>
<table>
<tbody>
<tr>
  <?php $cnt=0;?>
<?php foreach($videos_pager->getResults() as $videos): ?>
 
 <?php $cnt++;?>
<?php //$pic_url='albums/'.path2url($videos->getFilepath().'thumb_'.$videos->getFilename());?>
<?php $pic_url=path2url('/uploads/assets/videos/thumbnails/'.$videos->getFilename().'.png');?>

 <td><?php //echo link_to($videos->getId(), 'videos/show?id='.$videos->getId()) ?></td>
  <td>
 <?php echo link_to(image_tag($pic_url, ''), 'videos/show?id='.$videos->getId())?>
 <!-- <a href="<?php //echo '/frontend_dev.php/videos/show?id='.$videos->getId();?>"><img src="<?php //echo $pic_url;?>"></a>-->

  <br>views <?php echo $videos->getHits() ?>
  <div class="videos">
     <div class="interested_block" id="block_videos<?php echo $videos->getId() ?>">
        <?php //include_partial('videos/interested_user', array('videos' => $videos)) ?>
     </div>
   </div>
   
   <div class="question_body">
  
   <?php $video_owner=$videos->getsfGuardUser()->getUsername();?>
	 <div><?php echo link_to($video_owner, 'user/show?username='.$video_owner) ?>
	 <?php echo format_date($videos->getCtime(), 'p') ?></div>
    </div>
 </td>
 <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <?php if($cnt==4)
       {
	   $cnt=0;
	   ?>
     </tr>
	 <tr>
	 <?php }?>
	
</div>
<?php endforeach; ?>
</tbody>
</table>
<div id="videos_pager">
  <?php echo pager_navigation($videos_pager, $rule) ?>
</div>