<?php
// auto-generated by sfPropelCrud
// date: 2008/07/10 08:06:35
?>

	<!-- /header -->
	<!-- body -->
	<div id="bd">		
		<!--
		<div class="hdr-ad">
			<div>
				<script type="text/javascript">
google_ad_client = "pub-9464659474547085";
/* 728x90, created 8/26/08 */
google_ad_slot = "1178842710";
google_ad_width = 975;
google_ad_height = 90;

</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

			</div>
		</div>
		-->
		<!-- primary -->
		<div id="primary">
		    <?php include_partial('fp', array('videos'=>$videos)) ?>
			 <?php include_partial('video_list', array('videos'=>$videos)) ?>			
		</div>
		<!-- /primary -->
		<!-- secondary -->
		<div id="secondary">
			 <?php include_partial('comments') ?>			
		</div>
		<!-- /secondary -->
		<!-- related -->
		<div id="related">
			<div id="twm-right-ad">
				 <?php include_partial('ads') ?>
			</div>
			<?php //include_partial('alerts') ?>
		</div>
		<!-- /related -->
	</div>	
	<!-- /body -->