<?php
// auto-generated by sfPropelCrud
// date: 2008/05/28 05:50:45
?>
<?php use_helper('Object') ?>

<?php echo form_tag('editPlaylist/update') ?>

<?php echo object_input_hidden_tag($playlist_music, 'getPlaylistId') ?>
<?php echo object_input_hidden_tag($playlist_music, 'getMusicId') ?>


<hr />
<?php echo submit_tag('save') ?>
<?php if ($playlist_music->getPlaylistId() && $playlist_music->getMusicId()): ?>
  &nbsp;<?php echo link_to('delete', 'editPlaylist/delete?playlist_id='.$playlist_music->getPlaylistId().'&music_id='.$playlist_music->getMusicId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'editPlaylist/show?playlist_id='.$playlist_music->getPlaylistId().'&music_id='.$playlist_music->getMusicId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'editPlaylist/list') ?>
<?php endif; ?>
</form>
