<?php
// auto-generated by sfPropelCrud
// date: 2008/05/28 05:50:45
?>
<h1>editPlaylist</h1>

<table>
<thead>
<tr>
  <th>Playlist</th>
  <th>Music</th>
</tr>
</thead>
<tbody>
<?php foreach ($playlist_musics as $playlist_music): ?>
<tr>
    <td><?php echo link_to($playlist_music->getPlaylistId(), 'editPlaylist/show?playlist_id='.$playlist_music->getPlaylistId().'&music_id='.$playlist_music->getMusicId()) ?></td>
      <td><?php echo link_to($playlist_music->getMusicId(), 'editPlaylist/show?playlist_id='.$playlist_music->getPlaylistId().'&music_id='.$playlist_music->getMusicId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'editPlaylist/create') ?>
