default:
  has_layout:     on
  layout:         layout_profile 
showSuccess:
  stylesheets:    [/js/jcarousel/lib/jquery.jcarousel.css, /js/jcarousel/skins/tango/skin.css] 
  javascripts:    [jcarousel/lib/jquery.jcarousel.pack.js, jquery.carousel.js] 