<?php
// auto-generated by sfPropelCrud
// date: 2008/01/12 07:20:21
?>
<?php use_helper('Javascript', 'Global') ?>
<h2><?php echo $subscriber?>'s favorite playlists</h2>
<div id="fav_playlist">
<?php foreach ($playlists_pager->getResults() as $playlist): ?>
 <div class="user_playlist">
  <?php echo link_to($playlist->getName(), 'editPlaylist/show?playlist_id='.$playlist->getId()) ?>
  <?php if ($username_user_id==$user_id):?>
      <?php echo link_to_remote('[x]', array(
          'url'      => '@fav_playlist_remove?id='.$playlist->getId().'&username='.$subscriber,
          'update'   => 'fav_playlist',
		  'confirm'=>'Do you want to remove this playlist?',
          'loading'  => "Element.show('indicator')",
          'complete' => visual_effect('highlight', 'favorite_playlists'),
        )) ?> 		
		<?php endif;?> 
  </div>
<?php endforeach; ?>
</div>
<div class="pagination">
  <div id="photos_pager">
    <?php echo pager_navigation($playlists_pager, 'playlist/list') ?>
  </div>
</div>
