<?php
// auto-generated by sfPropelCrud
// date: 2008/07/10 08:06:35
?>
<?php use_helper('Object') ?>

<?php echo form_tag('video/update') ?>

<?php echo object_input_hidden_tag($video, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Filename*:</th>
  <td><?php echo object_input_tag($video, 'getFilename', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Hits:</th>
  <td><?php echo object_input_tag($video, 'getHits', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Rating:</th>
  <td><?php echo object_input_tag($video, 'getRating', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Vote:</th>
  <td><?php echo object_input_tag($video, 'getVote', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($video, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Approved*:</th>
  <td><?php echo object_input_tag($video, 'getApproved', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Raw ip:</th>
  <td><?php echo object_input_tag($video, 'getRawIp', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>User*:</th>
  <td><?php echo object_select_tag($video, 'getUserId', array (
  'related_class' => 'User',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($video->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'video/delete?id='.$video->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'video/show?id='.$video->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'video/list') ?>
<?php endif; ?>
</form>
